= Artifact Info
:!toc-title:
:!toc-placement:
:toc:

Get all information you need about your artifacts!

toc::[]

== About

By abstracting away all the details from the deployment pipeline, this module gives you easy access to info about your artifacts.

So you get the following outputs:

* The version of your artifact
* The S3 Bucket or ECR Registry of your artifact
* The path of your artifact.

This way, you don't need to know anything about the storage of your artifact or how to access it!

== Usage
To use this module, just add it to your terraform!

[source, hcl]
----
module "artifact_info" {
  source = "github.com/nsbno/terraform-aws-artifact-info?ref=x.y.z"

  application_name = "my-frontend-app"
}
----

== Examples

These examples show how you can deploy your application, and keep it up to date, using this module.

link:examples/container/main.tf[Container]::
Deploy your container to a fargate cluster.

link:examples/lambda/main.tf[Lambda]::
A simple lambda function!

== Relevant Repositories

link:https://github.com/nsbno/terraform-aws-delivery-pipeline[Delivery Pipeline]::
Set up a delivery pipeline for your team!
This is what will populate information about your artifacts.

link:https://github.com/nsbno/terraform-aws-pipeline-set-version[Set Version]::
The application that finds the artifact and updates SSM with the latest and greatest information.
This is deployed for you with the delivery pipeline!
